trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  clean: true

- script: |
    pip install virtualenv
    virtualenv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Setup Python Virtual Environment and Install Dependencies'

- script: |
    export LT_USERNAME="belalahmad"
    export LT_ACCESS_KEY="LT_UzeFPtk5kc9Z9eQSKXiqztgW3Tkx7lUfh0phyHFXWFQjbfp"
  displayName: 'Set LambdaTest Credentials'

- script: |
    behave features/test.feature --format html --outfile reports/test_report.html
  displayName: 'Run Behave Tests with HTML Report'

- task: Lambdatest.lambda-azure-pipeline-extention.showResults-task.LambdatestResults@1
  displayName: 'LambdaTest Results'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'reports' 
    artifact: 'HTMLReport'
    publishLocation: 'pipeline'
  displayName: 'Publish HTML Report'
